name: medical_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+40

environment:
  sdk: ">=2.11.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5

  get: ^4.6.5
  hexcolor: ^2.0.7
  flutter_svg: ^1.1.5
  swipe_to: ^1.0.2
  datetime_picker_formfield: ^2.0.1
  intl: ^0.17.0
  syncfusion_flutter_datepicker: ^20.2.50
  flutter_slidable: ^2.0.0
  image_picker: ^0.8.5+3
#  page_slider: ^0.0.2
  page_indicator: ^0.4.1
  syncfusion_flutter_sliders: ^20.2.50
  http: ^0.13.5
  shared_preferences: ^2.0.15
  email_validator: ^2.1.17
  toast: ^0.3.0
  mime: ^1.0.2
  connectivity: ^3.0.6
  cached_network_image: ^3.2.2
  overlay_support: ^2.0.1
#  firebase_messaging: 7.0.0
#  firebase_analytics: ^5.0.2
  flutter_masked_text2: ^0.9.1
  get_it: ^7.2.0
#  firebase_core:
#  flutter_local_notifications:
  keyboard_actions: ^4.0.1
  timeago: ^3.3.0
  age: ^0.0.1
  scroll_to_index: ^3.0.1
  after_layout: ^1.2.0
  sqflite: ^2.1.0
  path_provider: ^2.0.11
#  firebase_core:
#  cloud_firestore:
  flutter_search_bar: ^3.0.0-dev.1
  auto_size_text: ^3.0.0
  blinking_text: ^1.0.2
  json_store: ^2.0.0
  multi_select_flutter: ^4.1.2
  flutter_switch: ^0.3.2
  #  in_app_purchase: ^0.3.4
#  in_app_purchase: ^0.3.5+1
#  in_app_purchase:
#  flutter_inapp_purchase: ^5.3.1
  url_launcher: ^6.1.5
  dio: ^4.0.6
  otp_screen: ^0.0.3
  pattern_formatter: ^2.0.0
  device_info: ^2.0.3
  flutter_native_splash: ^2.2.9
  package_info_plus: ^1.4.3+1
  scrollable_positioned_list: ^0.3.4
  draggable_scrollbar: ^0.1.0
  whatsapp_unilink: ^2.0.2
  webview_flutter: ^4.0.7
  syncfusion_flutter_charts: ^20.4.54

  pdf: ^3.10.1
  printing: ^5.10.3


  flutter_localizations:
    sdk: flutter





dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - lib/json_config/files/
    - lib/json_config/files_pt/
#    - assets/fonts/nunito/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
     - family: Nunito
       fonts:
         - asset: assets/fonts/nunito/Nunito-Regular.ttf
         - asset: assets/fonts/nunito/Nunito-Bold.ttf
         - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
